//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3082
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AipoReminder.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AipoReminder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;!-- saved from url=({0}){1} --&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;noscript&gt;
        ///&lt;meta http-equiv=&quot;Refresh&quot; content=&quot;0; url={1}&quot; /&gt;
        ///&lt;/noscript&gt;
        ///&lt;/head&gt;
        ///&lt;body onload=&quot;document.pform.submit();window.focus();&quot;&gt;
        ///&lt;form name=&quot;pform&quot; action=&quot;{1}&quot; method=&quot;post&quot;&gt;
        ///&lt;input type=&quot;hidden&quot; name=&quot;username&quot; value=&quot;{2}&quot; /&gt;
        ///&lt;input type=&quot;hidden&quot; name=&quot;password&quot; value=&quot;{3}&quot; /&gt;
        ///&lt;input type=&quot;hidden&quot; name=&quot;action&quot; value=&quot;ALJLoginUser&quot; /&gt;
        ///&lt;input type=&quot;hidden&quot; name=&quot;org&quot; value=&quot;&quot; /&gt;
        ///&lt;/form&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string autologin {
            get {
                return ResourceManager.GetString("autologin", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon favicon_16 {
            get {
                object obj = ResourceManager.GetObject("favicon_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon favicon_16_blue {
            get {
                object obj = ResourceManager.GetObject("favicon_16_blue", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon favicon_16_red {
            get {
                object obj = ResourceManager.GetObject("favicon_16_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
